#!/usr/bin/python
import image_deformer.py


import argparse

parser = argparse.ArgumentParser(description='Run deformer.')
parser.add_argument('filepath', type=str,
                   help='the filepath to the heighmap')
parser.add_argument('max_height', type=float,
                   help='the max heigh')

args = parser.parse_args()



def main(filepath, max_height):
  """Gets user inputs and connects deformer.
  Args:
    filepath (str):
    max_height (float):
  """
  


if __name__ == "__main__":
   main()
