#!/usr/bin/env python

# Default imports
import argparse as _argparse
# Local imports
import image_deformer


def _parse_args():

    parser = _argparse.ArgumentParser(
        description='''
Apply deformation using a heightmap image
===========================================================================
        ''',
        formatter_class=_argparse.RawDescriptionHelpFormatter,
        epilog='''
===========================================================================
Provide:
  - full path to the image
  - max height for the deformation
===========================================================================
        '''
    )

    parser.add_argument(
        "-p",
        "--path",
        required=True,
        help='provide heightmap full path',
    )
    parser.add_argument(
        "-m",
        "--dmax",
        required=False,
        help='provide max height',
    )
    
def main():
    """Run deformer providing user inputs."""
    args = _parse_args()

    if args:
        filepath = args.path
        max_height = args.max_height
        image_deformer.main(filepath , max_height)
        print "Successful deformation."


if __name__ == "__main__":
    exit(main())
